from __future__ import annotations

import io
import re
import zipfile
from typing import Dict, List

import pandas as pd


def safe_filename(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", str(name)).strip("_")
    return cleaned or "measurement"


def _safe_sheet_name(name: str) -> str:
    cleaned = re.sub(r"[\[\]\:\*\?\/\\]", " ", str(name)).strip()
    return (cleaned or "Sheet")[:31]


def _autosize(writer: pd.ExcelWriter, sheet_name: str, df: pd.DataFrame):
    worksheet = writer.sheets[sheet_name]
    if df is None or df.empty:
        worksheet.set_column(0, 0, 28)
        return

    for col_idx, column in enumerate(df.columns):
        values = df[column].astype(str).head(200).tolist()
        width = min(max([len(str(column)), *[len(v) for v in values]]) + 2, 52)
        worksheet.set_column(col_idx, col_idx, width)


def _write_df(writer: pd.ExcelWriter, sheet_name: str, df: pd.DataFrame | None, index: bool = False):
    safe_name = _safe_sheet_name(sheet_name)
    workbook = writer.book
    header_format = workbook.add_format(
        {"bold": True, "bg_color": "#1F4E79", "font_color": "#FFFFFF", "border": 1, "text_wrap": True}
    )
    empty_df = pd.DataFrame({"Message / 提示": ["No data available / 暂无数据"]})
    target = df if df is not None and not df.empty else empty_df
    target.to_excel(writer, sheet_name=safe_name, index=index)
    worksheet = writer.sheets[safe_name]
    for col_idx, value in enumerate(target.columns):
        worksheet.write(0, col_idx, value, header_format)
    worksheet.freeze_panes(1, 0)
    worksheet.autofilter(0, 0, len(target), max(len(target.columns) - 1, 0))
    _autosize(writer, safe_name, target)


def create_summary_report(
    stats_df: pd.DataFrame,
    normality_df: pd.DataFrame,
    conclusions: List[Dict[str, str]],
    group_df: pd.DataFrame | None = None,
) -> bytes:
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
        conclusion_df = pd.DataFrame(conclusions) if conclusions else pd.DataFrame(
            {"English": ["No conclusion available."], "中文": ["暂无结论。"]}
        )
        overview = pd.DataFrame(
            {
                "Field / 字段": ["Generated By / 生成工具", "Report Type / 报告类型"],
                "Value / 内容": ["QC Measurement Capability Analyzer", "Excel Summary Report"],
            }
        )
        _write_df(writer, "Summary", overview)
        _write_df(writer, "Statistics", stats_df)
        capability_cols = [
            col
            for col in [
                "Measurement / 测量项目",
                "Group / 分组",
                "LSL / 下限",
                "USL / 上限",
                "Cp",
                "Cpk",
                "Cpk Grade / Cpk 等级",
                "Cp/Cpk Status / Cp/Cpk 状态",
                "Capability Conclusion EN / 能力英文结论",
                "Capability Conclusion CN / 能力中文结论",
            ]
            if stats_df is not None and col in stats_df.columns
        ]
        _write_df(writer, "Capability", stats_df[capability_cols] if capability_cols else None)
        _write_df(writer, "Normality Test", normality_df)
        _write_df(writer, "Auto Conclusion", conclusion_df)
        if group_df is not None and not group_df.empty:
            _write_df(writer, "Group Comparison", group_df)
    return output.getvalue()


def create_complete_analysis_excel(
    cleaned_data: pd.DataFrame,
    stats_df: pd.DataFrame,
    specs_df: pd.DataFrame,
    normality_df: pd.DataFrame,
    group_df: pd.DataFrame | None = None,
) -> bytes:
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
        _write_df(writer, "Cleaned Data", cleaned_data)
        _write_df(writer, "Analysis Results", stats_df)
        _write_df(writer, "Specification Table", specs_df)
        _write_df(writer, "Normality Test Results", normality_df)
        _write_df(writer, "Group Analysis Results", group_df)
    return output.getvalue()


def create_charts_zip(chart_files: Dict[str, bytes]) -> bytes:
    output = io.BytesIO()
    with zipfile.ZipFile(output, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_name, payload in chart_files.items():
            archive.writestr(file_name, payload)
    return output.getvalue()

