import io
import re
import zipfile

import pandas as pd


def safe_filename(name):
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", str(name)).strip("_")
    if cleaned:
        return cleaned
    return "measurement"


def _safe_sheet_name(name):
    """
    Excel sheet name must be <= 31 chars and cannot contain: []:*?/\
    """
    cleaned = re.sub(r"[\[\]\:\*\?\/\\]", " ", str(name)).strip()
    if not cleaned:
        cleaned = "Sheet"
    return cleaned[:31]


def _autosize(writer, sheet_name, df):
    """
    Safely adjust Excel column widths.
    """
    try:
        worksheet = writer.sheets[sheet_name]
    except Exception:
        return

    try:
        columns = list(df.columns)
    except Exception:
        return

    for idx, column in enumerate(columns):
        try:
            max_len = len(str(column))

            values = df[column].dropna().tolist()
            for value in values:
                try:
                    value_len = len(str(value))
                except Exception:
                    value_len = 0

                if value_len > max_len:
                    max_len = value_len

            width = max_len + 2

            if width > 52:
                width = 52

            if width < 10:
                width = 10

            worksheet.set_column(idx, idx, width)

        except Exception:
            try:
                worksheet.set_column(idx, idx, 18)
            except Exception:
                pass


def _write_df(writer, sheet_name, df, index=False):
    safe_name = _safe_sheet_name(sheet_name)

    if df is None:
        target = pd.DataFrame({"Message / 提示": ["No data available / 暂无数据"]})
    elif isinstance(df, pd.DataFrame) and df.empty:
        target = pd.DataFrame({"Message / 提示": ["No data available / 暂无数据"]})
    else:
        target = df

    if not isinstance(target, pd.DataFrame):
        try:
            target = pd.DataFrame(target)
        except Exception:
            target = pd.DataFrame({"Message / 提示": [str(target)]})

    target.to_excel(writer, sheet_name=safe_name, index=index)

    worksheet = writer.sheets[safe_name]
    workbook = writer.book

    try:
        header_format = workbook.add_format(
            {
                "bold": True,
                "bg_color": "#1F4E79",
                "font_color": "#FFFFFF",
                "border": 1,
                "text_wrap": True,
            }
        )

        for col_idx, value in enumerate(target.columns):
            worksheet.write(0, col_idx, str(value), header_format)
    except Exception:
        pass

    try:
        worksheet.freeze_panes(1, 0)
    except Exception:
        pass

    try:
        worksheet.autofilter(0, 0, len(target), max(len(target.columns) - 1, 0))
    except Exception:
        pass

    _autosize(writer, safe_name, target)


def create_summary_report(stats_df, normality_df, conclusions, group_df=None):
    output = io.BytesIO()

    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
        overview = pd.DataFrame(
            {
                "Field / 字段": [
                    "Generated By / 生成工具",
                    "Report Type / 报告类型",
                ],
                "Value / 内容": [
                    "QC Measurement Capability Analyzer",
                    "Excel Summary Report",
                ],
            }
        )

        try:
            conclusion_df = pd.DataFrame(conclusions)
        except Exception:
            conclusion_df = pd.DataFrame(
                {
                    "Conclusion / 结论": [str(conclusions)]
                }
            )

        if conclusion_df.empty:
            conclusion_df = pd.DataFrame(
                {
                    "English": ["No conclusion available."],
                    "中文": ["暂无结论。"],
                }
            )

        _write_df(writer, "Summary", overview)
        _write_df(writer, "Statistics", stats_df)

        capability_df = None
        if isinstance(stats_df, pd.DataFrame) and not stats_df.empty:
            capability_cols = []
            possible_cols = [
                "Measurement / 测量项目",
                "Group / 分组",
                "LSL / 下限",
                "USL / 上限",
                "Cp",
                "Cpk",
                "Cpk Grade / Cpk 等级",
                "Cp/Cpk Status / Cp/Cpk 状态",
                "Capability Conclusion EN / 能力英文结论",
                "Capability Conclusion CN / 能力中文结论",
            ]

            for col in possible_cols:
                if col in stats_df.columns:
                    capability_cols.append(col)

            if capability_cols:
                capability_df = stats_df[capability_cols]

        _write_df(writer, "Capability", capability_df)
        _write_df(writer, "Normality Test", normality_df)
        _write_df(writer, "Auto Conclusion", conclusion_df)

        if group_df is not None:
            _write_df(writer, "Group Comparison", group_df)

    return output.getvalue()


def create_complete_analysis_excel(cleaned_data, stats_df, specs_df, normality_df, group_df=None):
    output = io.BytesIO()

    with pd.ExcelWriter(output, engine="xlsxwriter") as writer:
        _write_df(writer, "Cleaned Data", cleaned_data)
        _write_df(writer, "Analysis Results", stats_df)
        _write_df(writer, "Specification Table", specs_df)
        _write_df(writer, "Normality Test Results", normality_df)
        _write_df(writer, "Group Analysis Results", group_df)

    return output.getvalue()


def create_charts_zip(chart_files):
    output = io.BytesIO()

    with zipfile.ZipFile(output, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_name, payload in chart_files.items():
            archive.writestr(file_name, payload)

    return output.getvalue()
